#use_frameworks!

platform :ios, '10.0'

target 'SJImagePickerController_Example' do
  pod 'SJImagePickerController', :path => '../'

  target 'SJImagePickerController_Tests' do
    inherit! :search_paths

    
  end
end
